name: "Deploy embed script"

on:
  push:
    branches:
      - main
    paths:
      - "packages/embeds/core/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies & build
        run: pnpm --filter @dub/embed-core build

      - name: Deploy to Cloudflare Pages (https://www.dubcdn.com/embed/script.js)
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_PAGES_API_KEY }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist/embed/script.js --project-name=dub-cdn --commit-dirty=true
          workingDirectory: packages/embeds/core
          packageManager: pnpm
